/**
 * Run registry and control endpoints.
 *
 * These are the only write endpoints in the system. Everything here either
 * mutates the run registry or pushes a command onto the control plane, and
 * nothing here talks to a worker directly -- the gateway's relationship with the
 * fleet is entirely mediated by subjects, which is why the fleet can scale
 * underneath it without the gateway holding a list of addresses.
 */

import { Router } from 'express';
import { CHAOS, EVENT } from '@scalescope/contracts';
import { appendEvent, broadcast, pub } from '@scalescope/bus';
import { pgPool } from '@scalescope/stores';
import { log } from '@scalescope/telemetry';
import {
  HttpError,
  startRun,
  stopRun,
  setSetpoint,
} from '../orchestrator.js';

/**
 * Run ids are generated by us and are always UUIDs, so anything that is not a
 * UUID is a bad request rather than a miss. Checking the shape at the edge means
 * the ClickHouse binder and the Postgres driver never see a value whose shape
 * they would have to reason about.
 */
export const UUID_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

export function requireUuid(req, res, next) {
  if (!UUID_RE.test(req.params.id || '')) {
    res.status(400).json({ error: 'invalid run id' });
    return;
  }
  next();
}

/** Columns the UI actually reads. Selecting * would ship config churn to the client. */
const RUN_COLUMNS = `
  id, name, profile, target_url, rounds, max_concurrency, duration_s, cooldown_s,
  slo_p95_ms, setpoint_ms, chaos, status, suite_id, suite_step, t0_ms,
  started_at, ended_at, peak_containers, peak_rps, peak_p95_ms, min_p95_ms,
  time_to_recover_s, container_seconds, total_requests, total_errors,
  est_cost_usd, linearity, is_showcase, notes, created_at`;

export function runsRoutes(ctx) {
  const router = Router();

  router.post('/api/runs', async (req, res, next) => {
    try {
      const result = await startRun(req.body || {});
      res.status(201).json(result);
    } catch (err) {
      next(err);
    }
  });

  /**
   * Registered before `/api/runs/:id` on purpose. Express matches in declaration
   * order, so with the parameterised route first this path would be validated as
   * a UUID and rejected with a 400 -- a classic and very confusing routing bug.
   */
  router.get('/api/runs/showcase', async (req, res, next) => {
    try {
      const { rows } = await pgPool.query(
        `SELECT ${RUN_COLUMNS} FROM runs
         WHERE status = 'completed'
         ORDER BY is_showcase DESC, peak_containers DESC NULLS LAST, peak_rps DESC
         LIMIT 1`,
      );
      res.json(rows[0] || null);
    } catch (err) {
      next(err);
    }
  });

  router.get('/api/runs', async (req, res, next) => {
    try {
      const limit = Math.min(200, Math.max(1, Number(req.query.limit) || 50));
      const { rows } = await pgPool.query(
        `SELECT ${RUN_COLUMNS} FROM runs ORDER BY created_at DESC LIMIT $1`,
        [limit],
      );
      res.json(rows);
    } catch (err) {
      next(err);
    }
  });

  router.get('/api/runs/:id', requireUuid, async (req, res, next) => {
    try {
      const { rows } = await pgPool.query(
        `SELECT ${RUN_COLUMNS} FROM runs WHERE id = $1`,
        [req.params.id],
      );
      if (!rows[0]) {
        res.status(404).json({ error: 'run not found' });
        return;
      }
      res.json(rows[0]);
    } catch (err) {
      next(err);
    }
  });

  router.post('/api/runs/:id/stop', requireUuid, async (req, res, next) => {
    try {
      const summary = await stopRun(req.params.id);
      res.json({ stopped: true, runId: req.params.id, summary });
    } catch (err) {
      next(err);
    }
  });

  /**
   * Live setpoint change. This is the autopilot's steering wheel: the operator
   * moves the latency target mid-run and the fleet's PID controllers retarget
   * without the run restarting. It is fire-and-forget because the authoritative
   * record of the change is the tick frames that follow it, not an ack.
   */
  router.post('/api/runs/:id/setpoint', requireUuid, (req, res) => {
    const setpointMs = Number(req.body?.setpointMs);
    if (!Number.isFinite(setpointMs) || setpointMs < 1 || setpointMs > 60_000) {
      res.status(400).json({ error: 'setpointMs must be between 1 and 60000' });
      return;
    }
    setSetpoint(req.params.id, Math.round(setpointMs));
    res.json({ ok: true, runId: req.params.id, setpointMs: Math.round(setpointMs) });
  });

  /**
   * Chaos injection. The command goes onto a queue subject so exactly one
   * injector acts on it -- two injectors both adding 200ms of latency would make
   * the resulting measurement unattributable.
   *
   * The event is appended here rather than by the chaos service so the run log
   * records the intent at the moment it was issued, even if the injector is
   * momentarily unavailable. An intent that did not take effect is still a fact
   * about the run.
   */
  router.post('/api/runs/:id/chaos', requireUuid, async (req, res, next) => {
    try {
      const runId = req.params.id;
      const kind = String(req.body?.kind || '').slice(0, 32);
      if (!kind) {
        res.status(400).json({ error: 'chaos kind is required' });
        return;
      }
      const command = {
        runId,
        kind,
        detail: req.body?.detail ?? null,
        durationS: Math.min(120, Math.max(1, Number(req.body?.durationS) || 20)),
        at: Date.now(),
      };

      pub(ctx.nc, CHAOS.COMMAND, command);
      await appendEvent(ctx.js, runId, EVENT.CHAOS, command, 'gateway');
      broadcast(ctx.nc, 'chaos', command);

      res.json({ ok: true, ...command });
    } catch (err) {
      next(err);
    }
  });

  /**
   * Mark a run as the showcase.
   *
   * Done as a single UPDATE over every row rather than a clear-then-set pair,
   * because the two-statement version has a window in which no run is the
   * showcase and the landing page has nothing to render. At this table size the
   * full scan is free.
   */
  router.post('/api/runs/:id/showcase', requireUuid, async (req, res, next) => {
    try {
      const { rowCount } = await pgPool.query(
        'UPDATE runs SET is_showcase = (id = $1)',
        [req.params.id],
      );
      log.info(`showcase set to ${req.params.id} (${rowCount} rows touched)`);
      res.json({ ok: true, runId: req.params.id });
    } catch (err) {
      next(err);
    }
  });

  return router;
}

export { HttpError };
